language: cpp
sudo: required
branches:
  only:
    - master
matrix:
  include:
    - os: linux
      deploy:
        edge:
          branch: v1.8.47 #work-around for broken Travis Deploy (https://github.com/travis-ci/travis-ci/issues/9312)
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        target_branch: deploy-linux
        local_dir: build/build
      dist: trusty      
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_C_COMPILER=gcc-6 -DNANOGUI_USE_GLAD=ON
        - make RegularMeshTexturing
        - mkdir build
        - zip -r build/gmcg-linux.zip bin
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - kubuntu-backports
          packages:
            - gcc-6
            - g++-6
            - cmake
            - xorg-dev
            - libglu1-mesa-dev
    - os: osx
      deploy:
        edge:
          branch: v1.8.47 #work-around for broken Travis Deploy (https://github.com/travis-ci/travis-ci/issues/9312)
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        target_branch: deploy-osx
        local_dir: build/export
      compiler: clang
      script:
        - mkdir build
        - cd build
        - cmake .. -DNANOGUI_USE_GLAD=ON
        - make RegularMeshTexturing
        - mkdir export
        - cp bin/RegularMeshTexturing.app/Contents/MacOS/RegularMeshTexturing bin/RegularMeshTexturing
        - zip export/gmcg-macos.zip bin/RegularMeshTexturing